// Code generated by "stringer -type=PromptOutputTag,PromptInputTag -linecomment -output prompt_tag_string.go"; DO NOT EDIT.

package autoklept

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PromptOutputText-0]
	_ = x[PromptOutputMarkdown-1]
	_ = x[PromptOutputSimple-2]
	_ = x[PromptOutputHugo-3]
}

const _PromptOutputTag_name = "TextMarkdownSimpleHugo"

var _PromptOutputTag_index = [...]uint8{0, 4, 12, 18, 22}

func (i PromptOutputTag) String() string {
	if i < 0 || i >= PromptOutputTag(len(_PromptOutputTag_index)-1) {
		return "PromptOutputTag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PromptOutputTag_name[_PromptOutputTag_index[i]:_PromptOutputTag_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PromptInputAll-0]
	_ = x[PromptInputBlog-1]
}

const _PromptInputTag_name = "AllBlog"

var _PromptInputTag_index = [...]uint8{0, 3, 7}

func (i PromptInputTag) String() string {
	if i < 0 || i >= PromptInputTag(len(_PromptInputTag_index)-1) {
		return "PromptInputTag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PromptInputTag_name[_PromptInputTag_index[i]:_PromptInputTag_index[i+1]]
}
